
INSERT INTO tm_translations (field_type, spanish_text, english_text) VALUES
('nav_title', 'Ir a la página de inicio de FEELOMOVE+', 'Go to FEELOMOVE+ homepage'),
('nav_title', 'Ver todos los festivales de música en España', 'See all music festivals in Spain'),
('nav_title', 'Ver todos los conciertos en España', 'See all concerts in Spain'),
('nav_title', 'Explorar artistas con eventos en España', 'Explore artists with events in Spain'),
('nav_title', 'Ofertas de conciertos con hotel incluido', 'Concert deals with hotel included'),
('nav_title', 'Explorar ciudades con eventos musicales', 'Explore cities with music events'),
('nav_title', 'Buscar hoteles para tu evento', 'Find hotels for your event'),
('nav_title', 'Ver mis eventos favoritos guardados', 'View my saved favorite events'),
('nav_title', 'Ver favoritos', 'View favorites'),
('footer_label', 'Directorio de eventos', 'Events directory'),
('footer_label', 'Conciertos por Ciudad', 'Concerts by City'),
('footer_label', 'Festivales por Ciudad', 'Festivals by City'),
('footer_label', 'Categorías', 'Categories'),
('footer_label', 'Tu destino para experiencias musicales inolvidables con el mejor alojamiento.', 'Your destination for unforgettable music experiences with the best accommodation.'),
('footer_label', 'Explorar', 'Explore'),
('footer_label', 'Descubre festivales de música en España', 'Discover music festivals in Spain'),
('footer_label', 'Explora destinos con eventos musicales', 'Explore destinations with music events'),
('footer_label', 'Ver artistas con conciertos en España', 'See artists with concerts in Spain'),
('footer_label', 'Explorar géneros musicales', 'Explore music genres'),
('footer_label', 'Conoce más sobre FEELOMOVE+', 'Learn more about FEELOMOVE+'),
('footer_label', 'Leer términos y condiciones de uso', 'Read terms and conditions of use'),
('footer_label', 'Consultar política de privacidad', 'View privacy policy'),
('footer_label', 'Información sobre uso de cookies', 'Information about cookie usage'),
('footer_label', 'Todos los derechos reservados.', 'All rights reserved.'),
('footer_label', 'Síguenos en Instagram', 'Follow us on Instagram'),
('footer_label', 'Síguenos en X (Twitter)', 'Follow us on X (Twitter)'),
('footer_label', 'Síguenos en Pinterest', 'Follow us on Pinterest'),
('hero_label', 'Entradas para Conciertos y Festivales en España', 'Tickets for Concerts and Festivals in Spain'),
('hero_label', '+ Hotel. Todo Resuelto.', '+ Hotel. All Sorted.'),
('hero_label', 'Compra entradas y reserva hotel cerca del evento. Ahorra tiempo y dinero con Feelomove+', 'Buy tickets and book a hotel near the venue. Save time and money with Feelomove+'),
('hero_label', 'Buscar por evento, artista, destino, género o mes...', 'Search by event, artist, destination, genre or month...'),
('hero_label', 'Buscando experiencias...', 'Searching experiences...'),
('hero_label', 'Artista', 'Artist'),
('hero_label', 'Destino', 'Destination'),
('hero_label', 'Género', 'Genre'),
('hero_label', 'No se encontraron resultados para', 'No results found for'),
('hero_label', 'Prueba con otro término o explora nuestros', 'Try another term or explore our'),
('hero_label', 'conciertos', 'tickets'),
('hero_label', 'Busca tu evento', 'Find your event'),
('hero_label', 'Encuentra tu concierto ideal', 'Find your ideal concert'),
('hero_label', 'Elige entradas + hotel', 'Choose tickets + hotel'),
('hero_label', 'Paquetes todo incluido', 'All-inclusive packages'),
('hero_label', 'Disfruta la música', 'Enjoy the music'),
('hero_label', 'Vive la experiencia', 'Live the experience'),
('section_heading', 'Los conciertos y festivales más populares de 2025', 'The most popular concerts and festivals of 2025'),
('section_heading', 'Los mejores festivales con hoteles cerca del recinto', 'The best festivals with hotels near the venue'),
('section_heading', 'Ver todos los festivales de música', 'See all music festivals'),
('section_heading', 'No hay festivales próximos', 'No upcoming festivals'),
('section_heading', 'Ver todos', 'See all'),
('section_heading', 'Conciertos en España 2025', 'Concerts in Spain 2025'),
('section_heading', 'Compra entradas para los conciertos más esperados', 'Buy tickets for the most anticipated concerts'),
('section_heading', 'Hoteles para Festivales y Conciertos', 'Hotels for Festivals and Concerts'),
('section_heading', 'Paquetes de entradas + alojamiento cerca del evento', 'Ticket + accommodation packages near the venue'),
('section_heading', 'Ver paquetes de eventos con hotel', 'See event packages with hotel'),
('section_heading', 'Ciudades con Eventos Musicales', 'Cities with Music Events'),
('section_heading', 'Ver todos los destinos con eventos', 'See all destinations with events'),
('section_heading', 'Artistas en Gira por España', 'Artists on Tour in Spain'),
('section_heading', 'Ver todos los artistas con conciertos', 'See all artists with concerts'),
('section_heading', 'Explorar todos los géneros musicales', 'Explore all music genres'),
('section_heading', 'La forma más inteligente de vivir la música en España', 'The smartest way to experience music in Spain'),
('about_page', 'Sobre Feelomove - Tu Portal de Eventos', 'About Feelomove - Your Events Portal'),
('about_page', 'Conectamos la pasión por la música con experiencias de alojamiento inolvidables', 'We connect the passion for music with unforgettable accommodation experiences'),
('about_page', 'Nuestra Misión', 'Our Mission'),
('about_page', 'Pasión Musical', 'Musical Passion'),
('about_page', 'Comodidad Garantizada', 'Guaranteed Comfort'),
('about_page', 'Experiencia Total', 'Total Experience'),
('about_page', 'Preguntas Frecuentes', 'Frequently Asked Questions'),
('about_page', 'Nuestro Equipo', 'Our Team'),
('eventos_page', 'Festivales y Conciertos', 'Festivals and Concerts'),
('eventos_page', 'Buscar eventos, ciudades o artistas...', 'Search events, cities or artists...'),
('eventos_page', 'Fecha (próximos primero)', 'Date (soonest first)'),
('eventos_page', 'Fecha (lejanos primero)', 'Date (latest first)'),
('eventos_page', 'Precio (menor a mayor)', 'Price (low to high)'),
('eventos_page', 'Precio (mayor a menor)', 'Price (high to low)'),
('eventos_page', 'Todas las ciudades', 'All cities'),
('eventos_page', 'Todos los artistas', 'All artists'),
('eventos_page', 'No se encontraron eventos', 'No events found'),
('eventos_page', 'Prueba ajustando los filtros o la búsqueda', 'Try adjusting the filters or search'),
('eventos_page', 'Cargando más eventos...', 'Loading more events...');
