
INSERT INTO tm_translations (spanish_text, english_text, field_type) VALUES
('Todos los géneros', 'All genres', 'filter_label'),
('Todas las fechas', 'All dates', 'filter_label'),
('Buscar eventos o artistas...', 'Search events or artists...', 'filter_label'),
('Buscar eventos o ciudades...', 'Search events or cities...', 'filter_label'),
('disponibles', 'available', 'page_label'),
('próximos', 'upcoming', 'page_label'),
('festivales', 'festivals', 'page_label'),
('eventos', 'events', 'page_label'),
('Temporada', 'Season', 'page_label'),
('Conciertos y Festivales en', 'Concerts and Festivals in', 'page_label'),
('Cargando la programación musical de', 'Loading the music schedule for', 'page_label'),
('Actualmente no hay eventos programados en', 'There are currently no events scheduled in', 'page_label'),
('Consulta otras ciudades cercanas o vuelve pronto para nuevas fechas.', 'Check nearby cities or come back soon for new dates.', 'page_label'),
('Mis Favoritos - Eventos Guardados', 'My Favorites - Saved Events', 'favoritos_page'),
('Tus conciertos y festivales favoritos guardados. Accede rápidamente a los eventos que más te interesan.', 'Your saved favorite concerts and festivals. Quickly access the events you care about most.', 'favoritos_page'),
('Mis Eventos Favoritos', 'My Favorite Events', 'favoritos_page'),
('No tienes eventos favoritos guardados', 'You have no saved favorite events', 'favoritos_page'),
('No hay favoritos aún', 'No favorites yet', 'favoritos_page'),
('Explora eventos y añade tus favoritos haciendo clic en el corazón', 'Explore events and add favorites by clicking the heart icon', 'favoritos_page'),
('Explorar Eventos', 'Explore Events', 'favoritos_page'),
('Por confirmar', 'To be confirmed', 'page_label'),
('Ver Detalles', 'View Details', 'page_label'),
('Line-up del Festival', 'Festival Line-up', 'festival_page'),
('No se encontraron eventos para este festival', 'No events found for this festival', 'festival_page'),
('Ver todos los festivales', 'See all festivals', 'festival_page'),
('Entradas', 'Tickets', 'festival_page'),
('No hay conciertos disponibles', 'No concerts available', 'festival_page'),
('Artistas destacados', 'Featured Artists', 'artista_page'),
('Destinos de', 'Destinations of', 'artista_page'),
('Artistas relacionados', 'Related Artists', 'artista_page'),
('Descubre todos los festivales y conciertos en España. Compra tus entradas y reserva tu hotel en el mismo lugar. Encuentra eventos de todos los géneros y ciudades.', 'Discover all festivals and concerts in Spain. Buy your tickets and book your hotel in the same place. Find events of all genres and cities.', 'eventos_page');
