
INSERT INTO tm_translations (spanish_text, english_text, field_type) VALUES
('Excelente', 'Excellent', 'ui'),
('Muy bien', 'Very good', 'ui'),
('Bien', 'Good', 'ui'),
('Aceptable', 'Acceptable', 'ui'),
('Regular', 'Average', 'ui'),
('Hotel confortable cerca del venue', 'Comfortable hotel near the venue', 'ui'),
('1 habitación x 1 noche impuestos incluidos', '1 room x 1 night taxes included', 'ui'),
('Añadir al pack', 'Add to pack', 'ui'),
('Añadido', 'Added', 'ui'),
('ver más', 'see more', 'ui'),
('ver menos', 'see less', 'ui'),
('+ entradas seleccionadas', '+ selected tickets', 'ui'),
('Enero', 'January', 'ui'),
('Febrero', 'February', 'ui'),
('Marzo', 'March', 'ui'),
('Abril', 'April', 'ui'),
('Mayo', 'May', 'ui'),
('Junio', 'June', 'ui'),
('Julio', 'July', 'ui'),
('Agosto', 'August', 'ui'),
('Septiembre', 'September', 'ui'),
('Octubre', 'October', 'ui'),
('Noviembre', 'November', 'ui'),
('Diciembre', 'December', 'ui'),
('Ciudad', 'City', 'ui'),
('Género', 'Genre', 'ui'),
('Mes', 'Month', 'ui'),
('Limpiar', 'Clear', 'ui'),
('Limpiar todo', 'Clear all', 'ui'),
('Limpiar filtros', 'Clear filters', 'ui'),
('Filtros', 'Filters', 'ui'),
('Todos', 'All', 'ui'),
('Aplicar', 'Apply', 'ui'),
('Todas las fechas', 'All dates', 'ui'),
('Fecha (próximos primero)', 'Date (upcoming first)', 'ui'),
('Fecha (lejanos primero)', 'Date (furthest first)', 'ui'),
('Precio (menor a mayor)', 'Price (low to high)', 'ui'),
('Precio (mayor a menor)', 'Price (high to low)', 'ui'),
('VER ENTRADAS', 'VIEW TICKETS', 'ui'),
('DISPONIBLE', 'AVAILABLE', 'ui'),
('A la venta:', 'On sale:', 'ui'),
('Por confirmar', 'TBC', 'ui'),
('FECHA', 'DATE', 'ui'),
('Ver entradas y detalles de', 'View tickets and details for', 'ui'),
('Conciertos, Gira y Entradas', 'Concerts, Tour & Tickets', 'ui'),
('Consulta todas las fechas confirmadas de la gira de', 'Check all confirmed tour dates for', 'ui'),
('fechas disponibles', 'dates available', 'ui'),
('Información actualizada de conciertos y venta de entradas oficial.', 'Updated concert info and official ticket sales.', 'ui'),
('Conciertos y gira en España', 'Concerts and tour in Spain', 'ui'),
('conciertos en España', 'concerts in Spain', 'ui'),
('Destinos de', 'Destinations for', 'ui'),
('Artistas relacionados', 'Related artists', 'ui'),
('Ordenar por', 'Sort by', 'ui'),
('Buscar eventos o ciudades...', 'Search events or cities...', 'ui'),
('No se encontraron eventos', 'No events found', 'ui'),
('Prueba ajustando los filtros o la búsqueda', 'Try adjusting the filters or search', 'ui'),
('Cargando más eventos...', 'Loading more events...', 'ui'),
('Artistas en Concierto', 'Artists in Concert', 'ui'),
('Encuentra eventos de tus artistas favoritos', 'Find events from your favorite artists', 'ui'),
('Artistas destacados con conciertos y festivales en España', 'Featured artists with concerts and festivals in Spain', 'ui'),
('Buscar artistas...', 'Search artists...', 'ui'),
('No se encontraron artistas', 'No artists found', 'ui'),
('Ver Eventos', 'View Events', 'ui'),
('Todas las ciudades', 'All cities', 'ui'),
('Todos los géneros', 'All genres', 'ui'),
('Todos los meses', 'All months', 'ui'),
('Ver conciertos de', 'View concerts by', 'ui')
ON CONFLICT (spanish_text) DO NOTHING;
