INSERT INTO tm_translations (spanish_text, english_text, field_type) VALUES
  ('Selecciona tus entradas', 'Select your tickets', 'ui'),
  ('¡Entradas añadidas! Ahora elige tu alojamiento', 'Tickets added! Now choose your accommodation', 'ui'),
  ('AGOTADO', 'SOLD OUT', 'ui'),
  ('DISPONIBLE', 'AVAILABLE', 'ui'),
  ('ÚLTIMAS', 'LAST ONES', 'ui'),
  ('Las entradas para este evento se han agotado', 'Tickets for this event are sold out', 'ui'),
  ('Empieza seleccionando tus entradas', 'Start by selecting your tickets', 'ui'),
  ('Elige las entradas y después añade un hotel para completar tu pack', 'Choose your tickets and then add a hotel to complete your pack', 'ui'),
  ('Completa tu pack con un hotel', 'Complete your pack with a hotel', 'ui'),
  ('Hotel añadido al pack', 'Hotel added to pack', 'ui'),
  ('Tu Pack', 'Your Pack', 'ui'),
  ('COMPLETO', 'COMPLETE', 'ui'),
  ('¡Pack completo! Entradas + Hotel', 'Pack complete! Tickets + Hotel', 'ui'),
  ('Entrada', 'Ticket', 'ui'),
  ('Cantidad', 'Quantity', 'ui'),
  ('gastos', 'fees', 'ui'),
  ('Reservar Entradas', 'Book Tickets', 'ui'),
  ('Reservar Hotel', 'Book Hotel', 'ui'),
  ('noches', 'nights', 'ui'),
  ('huéspedes', 'guests', 'ui'),
  ('Total por persona', 'Total per person', 'ui'),
  ('personas', 'people', 'ui'),
  ('entrada', 'ticket', 'ui'),
  ('entradas', 'tickets', 'ui'),
  ('Ver otros conciertos de', 'See other concerts by', 'ui'),
  ('Ver todos', 'See all', 'ui'),
  ('Error al cargar el evento', 'Error loading the event', 'ui'),
  ('Volver atrás', 'Go back', 'ui'),
  ('Reintentar', 'Retry', 'ui'),
  ('Fecha por confirmar', 'Date to be confirmed', 'ui'),
  ('Feelomove recomienda', 'Feelomove recommends', 'ui'),
  ('Hoteles en', 'Hotels in', 'ui'),
  ('Actividades', 'Activities', 'ui'),
  ('Mapa', 'Map', 'ui'),
  ('Todos', 'All', 'ui'),
  ('Ordenar por', 'Sort by', 'ui'),
  ('Distancia (más cercano)', 'Distance (nearest)', 'ui'),
  ('Precio (menor a mayor)', 'Price (low to high)', 'ui'),
  ('Precio (mayor a menor)', 'Price (high to low)', 'ui'),
  ('Valoración (mejor puntuada)', 'Rating (highest)', 'ui'),
  ('Estrellas (más estrellas)', 'Stars (most stars)', 'ui'),
  ('la zona', 'the area', 'ui'),
  ('VER MENOS', 'SEE LESS', 'ui'),
  ('VER', 'SEE', 'ui'),
  ('MÁS', 'MORE', 'ui'),
  ('Inicio', 'Home', 'ui'),
  ('Conciertos', 'Concerts', 'ui'),
  ('Festivales', 'Festivals', 'ui')
ON CONFLICT (spanish_text) DO UPDATE SET english_text = EXCLUDED.english_text;